site_name: investigraph
site_url: https://investigativedata.github.io/investigraph/
repo_url: https://github.com/investigativedata/investigraph
nav:
  - Overview: index.md
  - tutorial.md
  - install.md
  - Concepts:
    - concepts/catalog.md
    - concepts/dataset.md
    - concepts/entity.md
  - Documentation:
    - reference/index.md
    - reference/config.md
    - reference/cli.md
    - reference/extract.md
    - reference/transform.md
    - reference/load.md
    - reference/settings.md
  - Deployment:
    - deployment/services.md
    - deployment/docker.md
  - Stack:
    - stack/runpandarun.md
    - stack/followthemoney.md
    - stack/prefect.md
    - stack/nomenklatura.md
  - Updates:
    - changelogs/investigraph-etl.md
    - changelogs/runpandarun.md
theme:
  name: material
  font:
    text: Quicksand
    code: Inconsolata
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - navigation.footer
    - toc.follow
    - content.code.copy
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: material/web
      link: https://investigraph.vercel.app
    - icon: material/mail
      link: mailto:hi@investigativedata.org
    - icon: material/slack
      link: https://join.slack.com/t/investigativedata/shared_invite/zt-1ti4nojs7-GA_VKXowEbs5fWb7Ql9RqA
    - icon: material/github
      link: https://github.com/investigraph
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
